Pull Request post
NoCountryForGeeks/Blog pull request #22
Opened 2018-04-05 22:16 UTC by acnagrellos

2018-04-05 22:27 UTC, franmolmedo approved these changes

2018-04-06 06:08 UTC, IvanRodriCalleja approved these changes

2018-04-06 06:19 UTC, danimart1991 requested changes

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +Tener un repositorio de código es el primer paso del DoD, para poder subir el código y que no se quede en el ordenador del que trabajó en su equipo en local. Pero si vamos un poco más allá, en nuestr
La primera frase queda rara, además vendría bien definir DoD.

"las disyuntiva de como de responsables de como queda el código somos" esta frase también queda raro

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +Por ello, lo que hemos planteado aquí en el equipo son PRs con un rebase iterativo. ¿Que quiere decir esto? Que vamos a juntar todos los commits que hagamos en una PR en un solo commit, para que cuan
rebase i**n**teractivo

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +No os preocupéis de momento por el procedimiento, quedaos con el concepto. Si os imagináis una rama _develop_ a la cual se le hacen PRs constantemente desde otras ramas tipo _feature/12545_, al final
de manera cómoda.

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +Por tanto, si en una demo se ha olvidado poner cualquier cosa, no es culpa del desarrollador que lo hizo, es siempre culpa del equipo. Los proyecto__s__ son parte del equipo, es decir, no solo su pro
proyecto__s__

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +Si nos encontramos en develop y queremos llevar a cabo la tarea 23154, crearemos la rama _feature/{idtarea}_. (En el caso de _features/branches_, la nomenclatura para crear ramas será _feature/{idfea
Creo que la nomenclatura `feature/idFeature/idTask` no está permitida en git.

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +Uno de los problemas más comunes al hacer PRs, es que no tengamos develop actualizado. Por lo que tendremos que realizar un ````git fetch``` para actualizar el repo y, una vez actualizado, tendremos
\```git fetch``` only 3 `

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +Una vez pusheada la rama debemos ir al VSTS para poder crear la PR. Hay muchas maneras de crear la PR aunque normalmente si acabas de subir una rama, VSTS te dará la opción por defecto de que se acab
Add Italic to final commands

2018-04-06 06:19 UTC, danimart1991 commented on aclopez/PullRequests/PullRequest.md
> +![Build](http://sklyarenko.net/blog/2017/11/06/vsts-and-teamcity-commit-status-publisher/)
Broken image

2018-04-07 09:00 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +Si nos encontramos en develop y queremos llevar a cabo la tarea 23154, crearemos la rama _feature/{idtarea}_. (En el caso de _features/branches_, la nomenclatura para crear ramas será _feature/{idfea
¿No? Creo que te dejan poner dos niveles.

2018-04-07 09:29 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +Tener un repositorio de código es el primer paso del DoD, para poder subir el código y que no se quede en el ordenador del que trabajó en su equipo en local. Pero si vamos un poco más allá, en nuestr
He cambiado todo eso, a ver si asi queda mas claro.

2018-04-07 09:29 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +Por ello, lo que hemos planteado aquí en el equipo son PRs con un rebase iterativo. ¿Que quiere decir esto? Que vamos a juntar todos los commits que hagamos en una PR en un solo commit, para que cuan
Done

2018-04-07 09:30 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +No os preocupéis de momento por el procedimiento, quedaos con el concepto. Si os imagináis una rama _develop_ a la cual se le hacen PRs constantemente desde otras ramas tipo _feature/12545_, al final
Done

2018-04-07 09:30 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +Por tanto, si en una demo se ha olvidado poner cualquier cosa, no es culpa del desarrollador que lo hizo, es siempre culpa del equipo. Los proyecto__s__ son parte del equipo, es decir, no solo su pro
Eso es para poner la s en negrita.

2018-04-07 09:30 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +Uno de los problemas más comunes al hacer PRs, es que no tengamos develop actualizado. Por lo que tendremos que realizar un ````git fetch``` para actualizar el repo y, una vez actualizado, tendremos
Done.

2018-04-07 09:30 UTC, acnagrellos commented on aclopez/PullRequests/PullRequest.md
> +![Build](http://sklyarenko.net/blog/2017/11/06/vsts-and-teamcity-commit-status-publisher/)
Fixed

2018-04-09 18:36 UTC, danimart1991 approved these changes

2018-04-11 17:09 UTC, merged