Feature/destructuring
NoCountryForGeeks/Blog pull request #28
Opened 2018-09-19 07:05 UTC by acnagrellos

2018-09-19 07:17 UTC, danimart1991 approved these changes

2018-09-19 07:59 UTC, psanchezelena approved these changes
Muy buen post, muy bien explicado :)

2018-09-19 07:59 UTC, psanchezelena commented on aclopez/Destructuring/readme.md
> +Después de a ver visto la sintaxis del _destructuring_ seguro que os queda la duda de: ¿donde podría aplicar yo esto para que mi código fuese más limpio y legible? La destructuración se puede hacer e
Después de haber visto

2018-09-19 07:59 UTC, psanchezelena commented on aclopez/Destructuring/readme.md
> +Después de a ver visto la sintaxis del _destructuring_ seguro que os queda la duda de: ¿donde podría aplicar yo esto para que mi código fuese más limpio y legible? La destructuración se puede hacer e
¿dónde..

2018-09-19 07:59 UTC, psanchezelena commented on aclopez/Destructuring/readme.md
> +También es interesante en usar destructuring en las funciones para trabajar con _arrays_. Podéis verlas [en nuestro post de arrays](http://www.nocountryforgeeks.com/rambling-javascript-3-arrays/). En
También es interesante usar destructuring

2018-09-19 08:21 UTC, franmolmedo approved these changes

2018-09-19 08:21 UTC, franmolmedo commented on aclopez/Destructuring/readme.md
> +_Destructuring_, o destructuración en un lenguaje más hispanizado, es una nueva expresión de ES6 para Javascript que nos da la posibilidad de poder coger los datos de objetos o _arrays_ directamente
Más que expresión diría característica

2018-09-19 08:21 UTC, franmolmedo commented on aclopez/Destructuring/readme.md
> +_Destructuring_, o destructuración en un lenguaje más hispanizado, es una nueva expresión de ES6 para Javascript que nos da la posibilidad de poder coger los datos de objetos o _arrays_ directamente
Extraerlos a varaibles o constantes

2018-09-19 08:21 UTC, franmolmedo commented on aclopez/Destructuring/readme.md
> +const peopleBiggerThan40 = getPeople({ name: undefined, age: 40 });
no necesitas meter name ahí

2018-09-19 08:21 UTC, franmolmedo commented on aclopez/Destructuring/readme.md
> +const peopleBiggerThan40 = getPeople({ name: undefined, age: 40 });
No necesitas meter name, ya es undefined

2018-09-19 08:21 UTC, franmolmedo commented on aclopez/Destructuring/readme.md
> +const peopleBiggerThan40 = getPeople({ name: undefined, age: 40 });
Three times in a row

2018-09-19 08:21 UTC, franmolmedo commented on aclopez/Destructuring/readme.md
> +```
Este ejemplo no es bueno., no hace lo que dices

2018-09-19 11:16 UTC, ikeinyyo requested changes

2018-09-19 11:16 UTC, maktub82 commented on aclopez/Destructuring/readme.md
> +_Destructuring_ es una nueva característica muy potente del lenguaje que nos permite escribir código más legible, aunque como todo no hay que abusar de ella. Esto han sido pequeños ejemplos, pero seg
Conclusiones un poco pobres (nos pasa en todos los posts). Me falta info de qué impacto tiene sobre el rendimiento, si lo mejora, lo empeora... Y a lo mejor, algo de malas prácticas con el destructuring.

Por lo demás, está muy bien.

2018-09-19 11:16 UTC, maktub82 commented on aclopez/Destructuring/readme.md
> +```
Sí, esto hay que cambiarlo.

2018-09-19 16:02 UTC, IvanRodriCalleja reviewed
Me falta ver un ejemplo de la sintaxis que resuelve de no repetir propiedad a propiedad. Si tiene algún beneficio o no el usarlo en temas de rendimiento.

Puedes poner un ejemplo de destructuring que pilla lo que no has cogido.

Const { name, surname, ...test } = person;

2018-09-20 07:20 UTC, acnagrellos commented on aclopez/Destructuring/readme.md
> +```
Done

2018-09-25 13:21 UTC, ikeinyyo approved these changes

2018-09-25 13:23 UTC, merged