rambling-js-2
NoCountryForGeeks/Blog pull request #4
Opened 2017-08-27 20:48 UTC by franmolmedo

2017-08-28 16:00 UTC, danimart1991 approved these changes

2017-08-28 16:00 UTC, danimart1991 commented on franmolmedo/rambling-js-2/readme.md
> +El siguiente ejemplo también nos permite presentar un nuevo detalle reletivo a la sintaxis:
reletivo -> relativo

2017-08-28 16:00 UTC, danimart1991 commented on franmolmedo/rambling-js-2/readme.md
> +La mejora queda clara en cuanto a legibilidad. Imaginemos su uso en callbacks, donde ayudaran, sino a reducir, sí a mejorar, el temido `callback hell` en javascript.
callback hell in bold or italic, this is not code.

2017-08-28 16:00 UTC, danimart1991 commented on franmolmedo/rambling-js-2/readme.md
> +Todas son ventajas.
Todo son ventajas

2017-08-29 06:31 UTC, ikeinyyo requested changes

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Código totalmente correcto, pero quizás un pelín verboso para lo que realmente hace, que es la suma de dos números. De ahí partimos con las fat arrow function. En un primer momento podemos sustituir
~~pálabra~~ palabra

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Código totalmente correcto, pero quizás un pelín verboso para lo que realmente hace, que es la suma de dos números. De ahí partimos con las fat arrow function. En un primer momento podemos sustituir
~~quedándo~~ quedando

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Efectivamente, también hay puntos de que aclarar sobre la sintaxis relativo a los argumentos:
hay puntos ~~de~~ que aclarar sobre la sintaxis

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Todo lo que se ha comentado está bien, pero realmente, y con los ejemplos vistos, tampoco parece un cambio demasiado relevante.
muy ~~últil~~ útil su uso es en los predicados que ~~se~~ utilizamos en las funciones

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +¿Qué está ocurriendo?. Pues lo que todos sabíamos de antemano, el `this` dentro de la función que se ejecuta en el map, no es el que cabría esperarse (el objeto testObject, sino que es el contexto gl
+¿Qué está ocurriendo?~~.~~ Pues (Quita el punto)

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +¿Qué está ocurriendo?. Pues lo que todos sabíamos de antemano, el `this` dentro de la función que se ejecuta en el map, no es el que cabría esperarse (el objeto testObject, sino que es el contexto gl
el `this` dentro(,) de la función que se ejecuta en el map, no es el que cabría esperarse (O pones esa coma o quita la otra)

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Continuamos nuestro camino indangando sobre diversos aspectos de javascript. En este caso vamos a comentar sobre uno de los añadidos más relevantes que se hicieron con ES6 (ó EcmaScript 2015). Estamo
nuestro camino ~~indangando~~ indagando sobre diversos

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Continuamos nuestro camino indangando sobre diversos aspectos de javascript. En este caso vamos a comentar sobre uno de los añadidos más relevantes que se hicieron con ES6 (ó EcmaScript 2015). Estamo
javascript => JavaScript

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Hemos reducido algunos carácteres, pero la mejora tampoco es demasiado sustancial. Sin embargo, podemos seguir trabajando en la expresión. El siguiente aspecto en el que podemos dar cuenta, es que nu
reducido algunos ~~carácteres~~ caracteres, pero la mejora

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Hemos reducido algunos carácteres, pero la mejora tampoco es demasiado sustancial. Sin embargo, podemos seguir trabajando en la expresión. El siguiente aspecto en el que podemos dar cuenta, es que nu
return quedaría ~~ímplicita~~ implícita en la única expresión

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Creo que se intuye que extiendiendo su uso conseguiremos un código más claro y límpio.
intuye que ~~extiendiendo~~ extendiendo su uso conseguiremos

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Creo que se intuye que extiendiendo su uso conseguiremos un código más claro y límpio.
un código más claro y ~~límpio~~ limpio.

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Mostramos el típico ejemplo de un array de números, y queremos extraer aquellos cuyos valor sea mayor o igual que 5:
extraer aquellos ~~cuyos~~ cuyo valor sea mayor

2017-08-29 06:31 UTC, maktub82 commented on franmolmedo/rambling-js-2/readme.md
> +Todo lo comentado tiene su valor, pero donde realmente está el factor diferenciador de las fat arrow function respecto al empleo de las funciones tradicionales es en el cambio de comportamiento que h
ersona que haya trabajado con un código ~~javascript~~ JavaScript relativamente complejo

2017-08-29 08:06 UTC, ikeinyyo approved these changes

2017-08-29 08:12 UTC, acnagrellos approved these changes

2017-08-29 08:12 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Código totalmente correcto, pero quizás un pelín verboso para lo que realmente hace, que es la suma de dos números. De ahí partimos con las fat arrow function. En un primer momento podemos sustituir
```function``` => el formato no me deja escribirlo, pero function lo puedes poner como si fuera de codigo, con las tres comillas. Al igual que => que yo lo pondría tambien con las tres comillas de codigo.

2017-08-29 08:12 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Hemos reducido algunos carácteres, pero la mejora tampoco es demasiado sustancial. Sin embargo, podemos seguir trabajando en la expresión. El siguiente aspecto en el que podemos dar cuenta, es que nu
```return e``` => Como antes lo puedes poner con las tres comillas. y el return de despues tb

2017-08-29 08:12 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Sin embargo, cuando nos vamos a casos un poco más realistas, es donde empezamos a observar su valía. El ejemplo más claro en el que es muy últil su uso es en los predicados que se utilizamos en las f
muy últil su uso es en los predicados que ~se~ utilizamos en las funciones para tratar con colecciones

2017-08-29 08:12 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +¿Qué está ocurriendo?. Pues lo que todos sabíamos de antemano, el `this` dentro de la función que se ejecuta en el map, no es el que cabría esperarse (el objeto testObject, sino que es el contexto gl
yo pondria testObject y ES5 en cursiva. el title lo pondría con formato de codigo con las tres comillas y pondria ```this.title```

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Continuamos nuestro camino indagando sobre diversos aspectos de JavaScript. En este caso vamos a comentar sobre uno de los añadidos más relevantes que se hicieron con ES6 (ó EcmaScript 2015). Estamos
yo pondria ES6 y EnmaScript 2015 en cursiva

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +La mejora queda clara en cuanto a legibilidad. Imaginemos su uso en callbacks, donde ayudaran, sino a reducir, sí a mejorar, el temido *callback hell* en javascript.
SG: callbacks en cursiva.

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +La mejora queda clara en cuanto a legibilidad. Imaginemos su uso en callbacks, donde ayudaran, sino a reducir, sí a mejorar, el temido *callback hell* en javascript.
Yo le pondría un enlace a callback hell en javascript. Por ej: http://callbackhell.com/

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +* Utilizar el bind(this), a la hora de definir una función.
SG: `bind(this)` con las comillas de codigo

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Código totalmente correcto, pero quizás un pelín verboso para lo que realmente hace, que es la suma de dos números. De ahí partimos con las fat arrow function. En un primer momento podemos sustituir
SG: fat arrow function en cursiva.

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Todo lo comentado tiene su valor, pero donde realmente está el factor diferenciador de las fat arrow function respecto al empleo de las funciones tradicionales es en el cambio de comportamiento que h
SG: fat arrow en cursiva.

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Con el uso de las fat arrow function esto ya no será necesario, ya que, por defecto, `this` se va a referir al contexto donde la función haya sido declarada. Lo vemos con el ejemplo siguiente:
SG: fat arrow en cursiva como antes.

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +¿Qué está ocurriendo? Pues lo que todos sabíamos de antemano, el `this` dentro de la función que se ejecuta en el map no es el que cabría esperarse (el objeto testObject, sino que es el contexto glob
SG: testObject y ES5 en cursiva. Yo pondría no está definido el this.title que queda mas claro.

2017-08-29 08:53 UTC, acnagrellos commented on franmolmedo/rambling-js-2/readme.md
> +Mientras que, usando fat arrow function, el ejemplo quedaría:
SG: fat arrow en cursiva.

2017-08-29 09:20 UTC, merged