New post: generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad
NoCountryForGeeks/Blog pull request #6
Opened 2017-10-30 09:06 UTC by IvanRodriCalleja

New post: generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad

2017-10-30 09:40 UTC, franmolmedo approved these changes

2017-10-30 09:57 UTC, ikeinyyo requested changes
Muy buen Post Iván. Cambia los SVG por PNG o JPG para que se vean en el markdown. Cambia la ruta de algunas imágenes y revisa las faltas de ortografía.

Good Job!

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +![Cover Page](./images/CoverPage.svg)
Change svg by JPEG or PNG to see it in markdown.

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +## Como usar un SVG en la web
Cómo (con tilde)

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +## Generando un sprite SVG en mi aplicacion React, performance y accesibilidad
"#" (Título, H1). (Este no se incluye en Ghost, ya que el título del post va a parte)

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +
Todo el listado con punto (.) al final.

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +*	Nos ahorraremos peso de imágenes a la hora de descargar
**S:** No ahorramos...? Reducimos el peso...?

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +![Sprite SVG](./images/SpriteSVGProcess.svg)
svg to PNG or JPEG

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +![Icons fill](./images/IconsFill.jpg)
Image not found => iconsFill.jpg

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +Lo primero que vamos ha hacer es añadir a nuestro componente **Icon** los roles ``role='img'`` y ``role='presentation'`` uno ira en la etiqueta ``<svg>`` y el otro en la etiqueta``<use>``.
uno **irá** en la etiqueta ``<svg>``

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +También podemos hacer que cada uno de los vectores de nuestro svg reaccione a su propio ``<title>`` y ``<desc>`` esto nos puede venir bien en el ejemplo del mapa que tenemos, si hacemos los mismos pa
el ejemplo del mapa que tenemos ~~(,)~~ => (.) Si hacemos los mismos pasos que antes

2017-10-30 09:57 UTC, maktub82 commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +![Multi tooltip](./images/Multitooltip.gif)
Image not found => MultiTooltip.gif

2017-10-30 10:26 UTC, acnagrellos approved these changes
Muy buen post!! Me ha gustado mucho.

2017-10-30 10:26 UTC, acnagrellos commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +## ¿Que es SVG?
Qué

2017-10-30 10:26 UTC, acnagrellos commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +Para poder generar nuestro **sprite SVG** vamos a necesitar un loader que se encargue de ello, yo en mi caso voy a usar **svg-sprite-loader** en el siguiente, [enlace](https://github.com/kisenka/svg-
Quitaría la coma que hay detrás de siguiente

2017-10-30 10:26 UTC, acnagrellos commented on ivanrodri/generando-un-sprite-SVG-en-aplicacion-react-performance-y-accesibilidad/readme.md
> +hot: true,
Formatea esta parte y ponla al nivel de open.

2017-10-30 18:12 UTC, psanchezelena approved these changes

2017-10-31 08:52 UTC, ikeinyyo approved these changes

2017-10-31 08:55 UTC, merged